name: Deploy Blog (History + BGM)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Como es User Page, la base es '/'
env:
  BASE_PATH: '/'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (creates /vendor via postinstall)
        run: npm ci

      - name: Build manifests
        run: npm run build

      - name: Set BASE_PATH in index.html and 404.html
        run: |
          sed -i "s|window.SITE_BASE = '/';|window.SITE_BASE = '${BASE_PATH}';|" index.html
          sed -i "s|var BASE='/'|var BASE='${BASE_PATH}'|" 404.html

      - name: Prepare artifact
        run: |
          mkdir -p site
          cp -a index.html 404.html styles.css app.js .nojekyll site/
          cp -a assets content vendor site/
          [ -f README.md ] && cp README.md site/ || true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
